[project]
name = "constructor"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "osx-arm64", "win-64"]

[environments]
installer = ["installer"]
build = ["build", "build-linux", "build-osx", "build-win"]

[feature.installer.dependencies]
python = "*"

[feature.build.dependencies]
constructor = ">=3.9.2"
jaq = "*"

[feature.build.tasks]
specs = "pixi project export conda_explicit_spec --environment installer ./specs"
construct = """
rm -rf dist/installer/$CC_PLATFORM
&& constructor . --cache-dir build/.cache/constructor --output-dir dist/installer/$CC_PLATFORM
"""
platform = "pixi info --json | jaq -r '.platform'"

[feature.build-linux]
platforms = ["linux-64", "linux-aarch64", "linux-ppcle64"]
[feature.build-linux.tasks]
build = {depends-on = ["specs", "build-linux-64", "build-linux-aarch64", "build-linux-ppcle64"]}
build-linux-64 = "CC_PLATFORM=linux-64 pixi run construct"
build-linux-aarch64 = "CC_PLATFORM=linux-aarch64 pixi run construct"
build-linxu-ppcle64 = "CC_PLATFORM=linux-ppcle64 pixi run construct"
start = {depends-on = ["build"], cmd = """
rm -rf build/_installer_env_/
&& bash dist/installer/$(pixi run platform)/*.sh -fbp build/_installer_env_/
"""}

[feature.build-osx]
platforms = ["osx-64", "osx-arm64"]
[feature.build-osx.tasks]
build = {depends-on = ["specs", "build-osx-64", "build-osx-arm64"]}
build-osx-64 = "CC_PLATFORM=osx-64 pixi run construct"
build-osx-arm64 = "CC_PLATFORM=osx-arm64 pixi run construct"
start = {depends-on = ["build"], cmd = """
rm -rf build/_installer_env_/
&& bash dist/installer/$(pixi run platform)/*.sh -fbp build/_installer_env_/
"""}

[feature.build-win]
platforms = ["win-64"]
[feature.build-win.tasks]
build = {depends-on = ["specs", "build-win-64"]}
build-win-64 = "CC_PLATFORM=win-64 pixi run construct"
start = {depends-on = ["build"], cmd = '''
rm -rf build/_installer_env_/
&& start
  /wait
  ""
  \dist\installer\$(pixi run platform)\*.exe
  /InstallationType=JustMe
  /RegisterPython=0
  /S
  /D=build\_installer_env_\
'''}
